using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.CrestronThread;
using Crestron.SimplSharpPro.UI;
using MCCCD_AA140.Generated;

namespace MCCCD_AA140
{
    /// <summary>
    /// Application entry point. Registers touchpanels, instantiates control
    /// services, and runs the system power-up sequence after CIPNet is ready.
    /// </summary>
    public class ControlSystem : CrestronControlSystem
    {
        private MainContract _contract;
        private NvxRoutingService _nvx;
        private QsysAudioService _audio;
        private CameraService _cameras;
        private OccupancyController _occupancy;
        private SystemPowerController _power;

        // Touchpanels (IPIDs from the design spec)
        private Ts1070 _tsTabletop;
        private Tsw1070 _tswWall;

        public ControlSystem() : base()
        {
            try
            {
                Thread.MaxNumberOfUserThreads = 20;

                _tsTabletop = new Ts1070(0x03, this);
                _tswWall    = new Tsw1070(0x04, this);

                _tsTabletop.Register();
                _tswWall.Register();

                // Contract bridge — multi-panel support via the generated class.
                // NOTE: MainContract is auto-generated by Crestron Contract Editor
                // from contracts/MCCCD-AA140.cce. Constructor signature may vary
                // by Contract Editor version — adjust this call if needed.
                _contract = new MainContract(_tsTabletop, _tswWall);

                // Construct services (Initialize() runs after CIPNet is ready)
                _nvx       = new NvxRoutingService(_contract, this);
                _audio     = new QsysAudioService(_contract, this);
                _cameras   = new CameraService(_contract, this);
                _occupancy = new OccupancyController(_contract, this);
                _power     = new SystemPowerController(_contract, _nvx, _audio, this);
            }
            catch (System.Exception e)
            {
                ErrorLog.Error("ControlSystem ctor: {0}", e);
            }
        }

        public override void InitializeSystem()
        {
            try
            {
                _nvx.Initialize();
                _audio.Initialize();
                _cameras.Initialize();
                _occupancy.Initialize();
                _power.Initialize();

                // Wire occupancy transitions into the power controller
                _occupancy.OnOccupiedTransition  = () => _power.PowerUpSequence();
                _occupancy.OnSoftShutdownExpired = () => _power.PowerDownSequence();

                // Initial system-on (also handles D3 boot init: D2 source → D3)
                _power.PowerUpSequence();
            }
            catch (System.Exception e)
            {
                ErrorLog.Error("InitializeSystem: {0}", e);
            }
        }
    }
}
